export const bashUninstallTemplate = `#!/bin/bash
# cert-ctrl uninstallation script
# Generated by: {{BASE_URL}}
# Platform hint: {{PLATFORM}}-{{ARCHITECTURE}}

set -euo pipefail

# Overridable via env
PLATFORM="\${PLATFORM:-{{PLATFORM}}}"
ARCHITECTURE="\${ARCHITECTURE:-{{ARCHITECTURE}}}"
BASE_URL="\${BASE_URL:-{{BASE_URL}}}"
VERBOSE="\${VERBOSE:-{{VERBOSE}}}"
DRY_RUN="\${DRY_RUN:-{{DRY_RUN}}}"

INSTALL_DIR="\${INSTALL_DIR:-{{INSTALL_DIR}}}"
if [ -z "$INSTALL_DIR" ]; then
    INSTALL_DIR="/usr/local/bin"
fi

CONFIG_DIR="\${CONFIG_DIR:-{{CONFIG_DIR}}}"
if [ -z "$CONFIG_DIR" ]; then
    CONFIG_DIR="/etc/certctrl"
fi

STATE_DIR="\${STATE_DIR:-{{STATE_DIR}}}"
if [ -z "$STATE_DIR" ]; then
    STATE_DIR="/var/lib/certctrl"
fi

LOG_DIR="\${LOG_DIR:-{{LOG_DIR}}}"
if [ -z "$LOG_DIR" ]; then
    LOG_DIR="/var/log"
fi

SERVICE_NAME="\${SERVICE_NAME:-certctrl.service}"

# Flags
PURGE="false"
YES="false"

# Colors
RED='\x1b[0;31m'
GREEN='\x1b[0;32m'
YELLOW='\x1b[1;33m'
BLUE='\x1b[0;34m'
NC='\x1b[0m'

log_info() { echo -e "\${BLUE}[INFO]\${NC} $1" >&2; }
log_success() { echo -e "\${GREEN}[SUCCESS]\${NC} $1" >&2; }
log_warning() { echo -e "\${YELLOW}[WARNING]\${NC} $1" >&2; }
log_error() { echo -e "\${RED}[ERROR]\${NC} $1" >&2; }
log_verbose() { if [ "$VERBOSE" = "true" ]; then echo -e "\${BLUE}[VERBOSE]\${NC} $1" >&2; fi }

die() {
    log_error "$1"
    exit 1
}

usage() {
    cat >&2 <<EOF
cert-ctrl uninstall

Usage:
  curl -fsSL "\${BASE_URL}/uninstall.sh" | sudo bash

Options:
  --install-dir <dir>     Override install directory (default: /usr/local/bin)
  --service-name <name>   Override service name (default: certctrl.service)
  --config-dir <dir>      Override config directory (default: /etc/certctrl)
  --state-dir <dir>       Override state directory (default: /var/lib/certctrl)
  --log-dir <dir>         Override log directory (default: /var/log)
  --purge                 Also remove config/state/log data (DANGEROUS)
  --yes                   Do not prompt (required for --purge in noninteractive)
  --dry-run               Print actions without changing anything
  --verbose               Verbose logging
  -h, --help              Show help

Environment variables (alternatives to flags):
  INSTALL_DIR, SERVICE_NAME, CONFIG_DIR, STATE_DIR, LOG_DIR, DRY_RUN, VERBOSE
EOF
}

require_root() {
    if [ "\${EUID:-$(id -u)}" -ne 0 ]; then
        die "Run with sudo or as root."
    fi
}

find_command_path() {
    local cmd="$1"
    local resolved
    resolved=$(command -v "$cmd" 2>/dev/null || true)
    if [ -n "$resolved" ]; then
        echo "$resolved"
        return 0
    fi
    if [ -x "/sbin/$cmd" ]; then
        echo "/sbin/$cmd"
        return 0
    fi
    if [ -x "/usr/sbin/$cmd" ]; then
        echo "/usr/sbin/$cmd"
        return 0
    fi
    return 1
}

get_openrc_service_name() {
    local name="$SERVICE_NAME"
    if [[ "$name" == *.service ]]; then
        name="\${name%.service}"
    fi
    echo "$name"
}

get_freebsd_service_name() {
    local name="$SERVICE_NAME"
    if [[ "$name" == *.service ]]; then
        name="\${name%.service}"
    fi
    echo "$name"
}

detect_service_manager() {
    local uname_s
    uname_s=$(uname -s 2>/dev/null || true)

    if [ "$uname_s" = "FreeBSD" ]; then
        echo "freebsd-rcd"
        return 0
    fi

    if command -v rc-update >/dev/null 2>&1; then
        echo "openrc"
        return 0
    fi

    if command -v systemctl >/dev/null 2>&1; then
        echo "systemd"
        return 0
    fi

    echo "none"
}

run() {
    if [ "$DRY_RUN" = "true" ]; then
        log_info "DRY RUN: $*"
        return 0
    fi
    "$@"
}

remove_file_if_exists() {
    local path="$1"
    if [ -e "$path" ]; then
        log_info "Removing $path"
        run rm -f "$path"
    else
        log_verbose "Not present: $path"
    fi
}

remove_dir_if_exists() {
    local path="$1"
    if [ -d "$path" ]; then
        log_info "Removing directory $path"
        run rm -rf "$path"
    else
        log_verbose "Not present: $path"
    fi
}

stop_disable_systemd() {
    if ! command -v systemctl >/dev/null 2>&1; then
        return 0
    fi

    if systemctl list-unit-files "$SERVICE_NAME" >/dev/null 2>&1; then
        log_info "Stopping $SERVICE_NAME"
        run systemctl stop "$SERVICE_NAME" >/dev/null 2>&1 || true
        log_info "Disabling $SERVICE_NAME"
        run systemctl disable "$SERVICE_NAME" >/dev/null 2>&1 || true
    else
        log_verbose "systemd unit not registered: $SERVICE_NAME"
    fi

    local unit_path="/etc/systemd/system/$SERVICE_NAME"
    remove_file_if_exists "$unit_path"

    log_info "Reloading systemd"
    run systemctl daemon-reload >/dev/null 2>&1 || true
    run systemctl reset-failed >/dev/null 2>&1 || true
}

stop_disable_openrc() {
    local openrc_name
    openrc_name=$(get_openrc_service_name)

    local rc_service_bin=""
    if rc_service_bin=$(find_command_path rc-service 2>/dev/null); then
        log_info "Stopping $openrc_name"
        run "$rc_service_bin" "$openrc_name" stop >/dev/null 2>&1 || true
    fi

    local rc_update_bin=""
    if rc_update_bin=$(find_command_path rc-update 2>/dev/null); then
        log_info "Removing $openrc_name from default runlevel"
        run "$rc_update_bin" del "$openrc_name" default >/dev/null 2>&1 || true
    fi

    remove_file_if_exists "/etc/init.d/$openrc_name"
}

stop_disable_freebsd() {
    local rc_name
    rc_name=$(get_freebsd_service_name)

    local service_bin=""
    if service_bin=$(find_command_path service 2>/dev/null); then
        log_info "Stopping $rc_name"
        run "$service_bin" "$rc_name" stop >/dev/null 2>&1 || true
    fi

    local sysrc_bin=""
    if sysrc_bin=$(find_command_path sysrc 2>/dev/null); then
        log_info "Disabling $rc_name via sysrc"
        run "$sysrc_bin" "\${rc_name}_enable=NO" >/dev/null 2>&1 || true
    fi

    remove_file_if_exists "/usr/local/etc/rc.d/$rc_name"
}

confirm_purge() {
    if [ "$PURGE" != "true" ]; then
        return 0
    fi

    if [ "$YES" = "true" ]; then
        return 0
    fi

    cat >&2 <<EOF
\${YELLOW}[WARNING]\${NC} --purge will delete:
  - CONFIG_DIR: $CONFIG_DIR
  - STATE_DIR:  $STATE_DIR
  - Logs:       $LOG_DIR/certctrl.log and $LOG_DIR/certctrl.err.log (if present)

This may remove certificates, state, and configuration.
EOF

    printf "Type 'purge' to continue: " >&2
    local answer=""
    read -r answer
    if [ "$answer" != "purge" ]; then
        die "Purge cancelled."
    fi
}

parse_args() {
    while [ $# -gt 0 ]; do
        case "$1" in
            --install-dir)
                INSTALL_DIR="$2"; shift 2 ;;
            --service-name)
                SERVICE_NAME="$2"; shift 2 ;;
            --config-dir)
                CONFIG_DIR="$2"; shift 2 ;;
            --state-dir)
                STATE_DIR="$2"; shift 2 ;;
            --log-dir)
                LOG_DIR="$2"; shift 2 ;;
            --purge)
                PURGE="true"; shift ;;
            --yes)
                YES="true"; shift ;;
            --dry-run)
                DRY_RUN="true"; shift ;;
            --verbose)
                VERBOSE="true"; shift ;;
            -h|--help)
                usage; exit 0 ;;
            *)
                die "Unknown argument: $1 (try --help)" ;;
        esac
    done
}

main() {
    parse_args "$@"
    require_root

    local manager
    manager=$(detect_service_manager)

    log_info "Starting cert-ctrl uninstall"
    log_info "Install dir: $INSTALL_DIR"
    log_info "Service name: $SERVICE_NAME"
    log_info "Detected service manager: $manager"

    case "$manager" in
        systemd)
            stop_disable_systemd
            ;;
        openrc)
            stop_disable_openrc
            ;;
        freebsd-rcd)
            stop_disable_freebsd
            ;;
        *)
            log_warning "No supported service manager detected; attempting binary removal only"
            ;;
    esac

    remove_file_if_exists "$INSTALL_DIR/cert-ctrl"

    confirm_purge
    if [ "$PURGE" = "true" ]; then
        remove_dir_if_exists "$CONFIG_DIR"
        remove_dir_if_exists "$STATE_DIR"
        remove_file_if_exists "$LOG_DIR/certctrl.log"
        remove_file_if_exists "$LOG_DIR/certctrl.err.log"
    else
        log_info "Leaving config/state/logs in place (use --purge to remove)"
    fi

    log_success "Uninstall complete."
}

main "$@"
`;