export const powershellTemplate = `# cert-ctrl installation script (PowerShell)
# Generated by: {{BASE_URL}}
# Mirror: {{MIRROR_NAME}}
# Version: {{VERSION}}
# Platform: windows-{{ARCHITECTURE}}

param(
    [switch]$UserInstall,
    [string]$Version = "{{VERSION}}",
    [string]$InstallDir = "{{INSTALL_DIR}}",
    [switch]$Verbose,
    [switch]$Force,
    [switch]$ReplaceConfig,
    [switch]$ReplaceService,
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

function Get-SystemArchitecture {
    try {
        $runtimeType = [System.Runtime.InteropServices.RuntimeInformation]
        $property = $runtimeType.GetProperty('OSArchitecture')
        if ($property) {
            $value = $property.GetValue($null)
            if ($value) {
                return $value.ToString()
            }
        }
    }
    catch {
        # Ignore and try alternate mechanisms
    }

    try {
        $os = Get-CimInstance Win32_OperatingSystem -ErrorAction Stop
        if ($os.OSArchitecture) {
            return $os.OSArchitecture
        }
    }
    catch {
        try {
            $os = Get-WmiObject Win32_OperatingSystem -ErrorAction Stop
            if ($os.OSArchitecture) {
                return $os.OSArchitecture
            }
        }
        catch {
            # Fall through
        }
    }

    if ([Environment]::Is64BitOperatingSystem) {
        return 'x64'
    }

    return 'x86'
}

function Write-Info($Message) {
    Write-Host "[INFO] $Message"
}

function Write-Success($Message) {
    Write-Host "[SUCCESS] $Message" -ForegroundColor Green
}

function Write-WarningMessage($Message) {
    Write-Warning $Message
}

function Write-ErrorMessage($Message) {
    Write-Error $Message
}

function Test-Administrator {
    $currentUser = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($currentUser)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Get-InstalledCertCtrlVersion {
    param(
        [string]$BinaryPath
    )

    if (-not (Test-Path $BinaryPath)) {
        return $null
    }

    try {
        return (& $BinaryPath --version 2>$null | Select-Object -First 1)
    }
    catch {
        return $null
    }
}

$serviceName = "CertCtrlAgent"
$serviceDisplayName = "Cert Ctrl Agent"
$serviceDescription = "Maintains device certificates and polls the cert-ctrl control plane."
$serviceArgs = "--keep-running"

function Register-CertCtrlService {
    param(
        [string]$BinaryPath,
        [bool]$IsUserInstall,
        [bool]$ReplaceService
    )

    if ($IsUserInstall) {
        Write-Info "User install selected; skipping Windows service registration."
        return $false
    }

    if (-not (Test-Administrator)) {
        Write-WarningMessage "Administrator privileges are required to register the Windows service. Skipping."
        return $false
    }

    $imagePath = '"' + $BinaryPath + '" ' + $serviceArgs

    try {
        $existing = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
        if ($existing) {
            if (-not $ReplaceService) {
                Write-Info "Preserving existing Windows service '$serviceName'. Use -ReplaceService to regenerate it."
                if ($existing.Status -ne 'Running') {
                    Start-Service -Name $serviceName -ErrorAction Stop
                }
                return $true
            }

            if ($existing.Status -eq 'Running') {
                Stop-Service -Name $serviceName -Force -ErrorAction Stop
            }
            $configOutput = & sc.exe config $serviceName 'binPath=' $imagePath 'start=' 'auto' 'DisplayName=' $serviceDisplayName 2>&1
            if ($LASTEXITCODE -ne 0) {
                throw "sc.exe config failed: $configOutput"
            }
            & sc.exe description $serviceName $serviceDescription | Out-Null
            Start-Service -Name $serviceName -ErrorAction Stop
            Write-Success "Windows service '$serviceName' updated."
            return $true
        }

        New-Service -Name $serviceName -BinaryPathName $imagePath -DisplayName $serviceDisplayName -Description $serviceDescription -StartupType Automatic -ErrorAction Stop
        Start-Service -Name $serviceName -ErrorAction Stop
        Write-Success "Windows service '$serviceName' registered."
        return $true
    }
    catch {
        Write-WarningMessage "Failed to configure Windows service '$serviceName': $($_.Exception.Message)"
        return $false
    }
}

$archSlug = "{{ARCHITECTURE}}"
if ([string]::IsNullOrWhiteSpace($archSlug)) {
    $archSlug = "x64"
}

$systemArchitecture = Get-SystemArchitecture
switch -regex ($systemArchitecture) {
    'arm64|aarch64' { $archSlug = 'arm64'; break }
    'arm' { $archSlug = 'arm'; break }
    'x86|x64|amd64|86|64' { $archSlug = 'x64'; break }
    default { $archSlug = 'x64' }
}

$paramUserInstall = $false
if ($PSBoundParameters.ContainsKey('UserInstall') -and $UserInstall.IsPresent) {
    $paramUserInstall = $true
}

$paramForceInstall = ([bool]$Force) -or ("{{FORCE}}" -eq "true")
$paramReplaceConfig = ([bool]$ReplaceConfig) -or ("{{REPLACE_CONFIG}}" -eq "true")
$paramReplaceService = ([bool]$ReplaceService) -or ("{{REPLACE_SERVICE}}" -eq "true")


$installPath = if ($InstallDir) {
    $InstallDir
} else {
    if ($paramUserInstall) {
        Join-Path $env:LOCALAPPDATA "Programs\\cert-ctrl"
    } else {
        "C:\\Program Files\\cert-ctrl"
    }
}

if ($paramUserInstall -and -not (Test-Administrator)) {
    Write-Info "User-mode installation selected; administrator rights are not required."
}
elseif (-not $paramUserInstall -and -not (Test-Administrator)) {
    $userInstallPath = Join-Path $env:LOCALAPPDATA "Programs\cert-ctrl"
    Write-ErrorMessage "Administrator privileges are required to install to '$installPath'."
    Write-Info "Option 1: Close this window, re-launch Windows PowerShell or PowerShell with 'Run as administrator', then rerun install.ps1."
    Write-Info "Option 2: Run the installer with -UserInstall for a per-user installation at '$userInstallPath'."
    Write-Info "Option 3: Specify -InstallDir to point at a directory you already own."
    exit 1
}

$destinationBinary = Join-Path $installPath 'cert-ctrl.exe'

if (-not $paramForceInstall -and -not $paramReplaceConfig -and -not $paramReplaceService) {
    $existingVersion = Get-InstalledCertCtrlVersion -BinaryPath $destinationBinary
    if ($existingVersion) {
        $normalizedExisting = $existingVersion.TrimStart('v')
        $normalizedRequested = $Version.TrimStart('v')
        if ($normalizedExisting -eq $normalizedRequested) {
            Write-Success "cert-ctrl $existingVersion is already installed at $destinationBinary"
            Write-Host ""
            Write-Info "To reinstall anyway, choose one of the following:"
            Write-Info "  1. URL parameter:   irm \"{{BASE_URL}}/install.ps1?force=1\" | iex"
            Write-Info "  2. Download + flag: irm \"{{BASE_URL}}/install.ps1\" -OutFile install.ps1; .\\install.ps1 -Force"
            Write-Info "  3. Remove existing: Remove-Item -Force -Path \"$destinationBinary\"; irm \"{{BASE_URL}}/install.ps1?force=1\" | iex"
            exit 0
        }

        Write-Info "Existing install version $existingVersion differs from requested $Version; continuing with upgrade."
    }
}

$mirrorUrl = "{{MIRROR_URL}}"
if ($mirrorUrl -eq "{{BASE_URL}}/releases/proxy") {
    $packageUrl = "$mirrorUrl/$Version/cert-ctrl-windows-$archSlug.zip"
} else {
    $packageUrl = "$mirrorUrl/{{GITHUB_REPO_OWNER}}/{{GITHUB_REPO_NAME}}/releases/download/$Version/cert-ctrl-windows-$archSlug.zip"
}

$tempDir = New-Item -ItemType Directory -Path ([System.IO.Path]::GetTempPath()) -Name ("cert-ctrl-" + [System.Guid]::NewGuid().ToString())
$zipPath = Join-Path $tempDir "cert-ctrl.zip"
$checksumPath = Join-Path $tempDir "cert-ctrl.zip.sha256"

Write-Info "Downloading cert-ctrl $Version..."
Invoke-WebRequest -Uri $packageUrl -OutFile $zipPath -UseBasicParsing
Invoke-WebRequest -Uri ($packageUrl + '.sha256') -OutFile $checksumPath -UseBasicParsing

$expectedChecksum = ((Get-Content -Path $checksumPath -Raw).Trim() -split '\\s+')[0].ToLowerInvariant()
$actualChecksum = (Get-FileHash -Path $zipPath -Algorithm SHA256).Hash.ToLowerInvariant()
if ([string]::IsNullOrWhiteSpace($expectedChecksum)) {
    throw 'Release checksum file is empty; refusing an unverified installation.'
}
if ($expectedChecksum -ne $actualChecksum) {
    throw "Checksum mismatch (expected $expectedChecksum, got $actualChecksum)."
}
Write-Success "Checksum verified."

if ($DryRun -or ("{{DRY_RUN}}" -eq "true")) {
    Write-Info "DRY RUN: Installation files prepared at $tempDir"
    exit 0
}

Expand-Archive -Path $zipPath -DestinationPath $tempDir -Force

New-Item -ItemType Directory -Force -Path $installPath | Out-Null

# Prepare cert-ctrl default config/runtime directories.
# cert-ctrl defaults:
#   %ProgramData%\\certctrl\\config
#   %ProgramData%\\certctrl\\runtime
$programData = $env:ProgramData
if ([string]::IsNullOrWhiteSpace($programData)) {
    $programData = "C:\\ProgramData"
}
$defaultBaseDir = Join-Path $programData 'certctrl'
$defaultConfigDir = Join-Path $defaultBaseDir 'config'
$defaultRuntimeDir = Join-Path $defaultBaseDir 'runtime'

try {
    New-Item -ItemType Directory -Force -Path $defaultConfigDir | Out-Null
    New-Item -ItemType Directory -Force -Path $defaultRuntimeDir | Out-Null
}
catch {
    Write-WarningMessage "Failed to create cert-ctrl default directories under ProgramData: $($_.Exception.Message)"
}

# Install a CA bundle for OpenSSL-based TLS verification on Windows.
# The agent auto-detects 'cacert.pem' in config/runtime dirs when verify_paths is empty.
$installedCaBundle = Join-Path $defaultConfigDir 'cacert.pem'
if ($paramReplaceConfig -or -not (Test-Path $installedCaBundle)) {
    $bundledCa = Join-Path $tempDir 'cacert.pem'
    if (-not (Test-Path $bundledCa)) {
        $bundledCa = Join-Path $tempDir 'certs\\cacert.pem'
    }

    if (Test-Path $bundledCa) {
        try {
            Copy-Item -Path $bundledCa -Destination $installedCaBundle -Force
            Write-Info "Installed CA bundle to $installedCaBundle"
        }
        catch {
            Write-WarningMessage "Failed to copy bundled cacert.pem to ProgramData: $($_.Exception.Message)"
        }
    }
    else {
        # Fallback: download a CA bundle if the release archive does not include one.
        # This is only used to bootstrap TLS verification for OpenSSL builds.
        try {
            Write-Info "Downloading CA bundle (cacert.pem) to enable TLS verification..."
            $caUrlCandidates = @(
                "{{BASE_URL}}/assets/cacert.pem",
                'https://curl.se/ca/cacert.pem'
            )
            $downloaded = $false
            foreach ($candidateUrl in $caUrlCandidates) {
                try {
                    Invoke-WebRequest -Uri $candidateUrl -OutFile $installedCaBundle -UseBasicParsing
                    Write-Info "Downloaded CA bundle from $candidateUrl"
                    $downloaded = $true
                    break
                }
                catch {
                    # Try next candidate
                }
            }
            if (-not $downloaded) {
                throw "All CA bundle download URLs failed"
            }
        }
        catch {
            Write-WarningMessage "Unable to install CA bundle automatically. WebSocket TLS verification may fail on Windows."
            Write-Info "Fix: place a CA bundle at $installedCaBundle or set websocket_config.json verify_paths."
        }
    }
}

$binaryPath = Join-Path $tempDir 'cert-ctrl.exe'
if (-not (Test-Path $binaryPath)) {
    $binaryPath = Join-Path $tempDir 'bin\\cert-ctrl.exe'
}

if (-not (Test-Path $binaryPath)) {
    Write-ErrorMessage "cert-ctrl executable not found in downloaded archive"
    exit 1
}

$candidateVersion = (& $binaryPath --version 2>$null | Select-Object -First 1)
if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($candidateVersion)) {
    throw 'Downloaded cert-ctrl binary failed its pre-install version check.'
}
if ($candidateVersion.Trim() -ne $Version.Trim()) {
    throw "Downloaded binary version mismatch: expected $Version, got $candidateVersion."
}

$destinationBinary = Join-Path $installPath 'cert-ctrl.exe'

$serviceWasRunning = $false
if (-not $paramUserInstall) {
    $existingService = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
    if ($existingService -and $existingService.Status -eq 'Running') {
        try {
            Write-Info "Stopping Windows service '$serviceName' before updating binary..."
            Stop-Service -Name $serviceName -Force -ErrorAction Stop
            $existingService.WaitForStatus([System.ServiceProcess.ServiceControllerStatus]::Stopped, [TimeSpan]::FromSeconds(30))
            $serviceWasRunning = $true
        }
        catch {
            throw "Unable to stop service '$serviceName'; refusing to replace a running installation. $($_.Exception.Message)"
        }
    }
}

$backupBinary = Join-Path $tempDir 'cert-ctrl.previous.exe'
$hadExistingBinary = Test-Path $destinationBinary
if ($hadExistingBinary) {
    Copy-Item -Path $destinationBinary -Destination $backupBinary -Force
}

try {
    $stagedBinary = Join-Path $installPath ('.cert-ctrl.install.' + [System.Guid]::NewGuid().ToString('N') + '.exe')
    Copy-Item -Path $binaryPath -Destination $stagedBinary -Force
    Move-Item -Path $stagedBinary -Destination $destinationBinary -Force

    $serviceInstalled = Register-CertCtrlService -BinaryPath $destinationBinary -IsUserInstall:$paramUserInstall -ReplaceService:$paramReplaceService
    if (-not $paramUserInstall -and -not $serviceInstalled) {
        throw "Failed to configure Windows service '$serviceName'."
    }

    if ($serviceWasRunning) {
        $runningService = Get-Service -Name $serviceName -ErrorAction Stop
        $runningService.WaitForStatus([System.ServiceProcess.ServiceControllerStatus]::Running, [TimeSpan]::FromSeconds(30))
    }
}
catch {
    Write-ErrorMessage "Upgrade failed; restoring the previous cert-ctrl binary. $($_.Exception.Message)"
    if ($hadExistingBinary -and (Test-Path $backupBinary)) {
        Copy-Item -Path $backupBinary -Destination $destinationBinary -Force
    }
    elseif (-not $hadExistingBinary) {
        Remove-Item -Path $destinationBinary -Force -ErrorAction SilentlyContinue
    }
    if ($serviceWasRunning) {
        Start-Service -Name $serviceName -ErrorAction SilentlyContinue
    }
    throw
}

Write-Success "cert-ctrl installed at $destinationBinary"
Write-Info "Binary directory: $installPath"
$normalizedInstallPath = $installPath.TrimEnd('\\')
$pathEntries = $env:PATH -split ';'
$pathPresent = $pathEntries | Where-Object { $_.TrimEnd('\\') -ieq $normalizedInstallPath }
if (-not $pathPresent) {
    $originalPath = $env:PATH
    if (-not ($env:PATH -like "*$normalizedInstallPath*")) {
        $env:PATH = ($originalPath.TrimEnd(';')) + ';' + $installPath
        Write-Info "Added $installPath to PATH for this PowerShell session."
        Write-Info "Verify now with: where.exe cert-ctrl"
    }

    $userPath = [Environment]::GetEnvironmentVariable("PATH", [EnvironmentVariableTarget]::User)
    if ([string]::IsNullOrWhiteSpace($userPath)) {
        $userPath = $originalPath
    }
    $userEntries = $userPath -split ';'
    $userHasPath = $userEntries | Where-Object { $_.TrimEnd('\\') -ieq $normalizedInstallPath }
    if (-not $userHasPath) {
        $newUserPath = if ([string]::IsNullOrWhiteSpace($userPath)) {
            $installPath
        } else {
            ($userPath.TrimEnd(';')) + ';' + $installPath
        }
        [Environment]::SetEnvironmentVariable("PATH", $newUserPath, [EnvironmentVariableTarget]::User)
        Write-Info "Persisted install directory to current user's PATH."
    }

    if (Test-Administrator) {
        $machinePath = [Environment]::GetEnvironmentVariable("PATH", [EnvironmentVariableTarget]::Machine)
        if ([string]::IsNullOrWhiteSpace($machinePath)) {
            $machinePath = $originalPath
        }
        $machineEntries = $machinePath -split ';'
        $machineHasPath = $machineEntries | Where-Object { $_.TrimEnd('\\') -ieq $normalizedInstallPath }
        if (-not $machineHasPath) {
            $newMachinePath = if ([string]::IsNullOrWhiteSpace($machinePath)) {
                $installPath
            } else {
                ($machinePath.TrimEnd(';')) + ';' + $installPath
            }
            [Environment]::SetEnvironmentVariable("PATH", $newMachinePath, [EnvironmentVariableTarget]::Machine)
            Write-Info "Persisted install directory to machine PATH."
        }
    } else {
        Write-Info "Re-open PowerShell to use cert-ctrl without specifying the full path."
    }
}
if ($serviceInstalled) {
    Write-Info "Windows service '$serviceName' is running."
} elseif (-not $paramUserInstall) {
    $manualCommand = "sc create $serviceName binPath=\"" + $destinationBinary + "\" " + $serviceArgs
    Write-Info "Register later as a service with: $manualCommand"
}
$statusCommand = 'Get-Service ' + $serviceName
Write-Info "Service status: $statusCommand"
Remove-Item -Path $tempDir -Recurse -Force -ErrorAction SilentlyContinue
`;
