export const powershellUninstallTemplate = `# cert-ctrl uninstallation script (PowerShell)
# Generated by: {{BASE_URL}}
# Platform: windows-{{ARCHITECTURE}}

param(
    [switch]$UserInstall,
    [string]$InstallDir,
    [switch]$Purge,
    [switch]$Yes,
    [switch]$DryRun,
    [switch]$Verbose
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

function Write-Info($Message) { Write-Host "[INFO] $Message" }
function Write-Success($Message) { Write-Host "[SUCCESS] $Message" -ForegroundColor Green }
function Write-WarningMessage($Message) { Write-Warning $Message }
function Write-ErrorMessage($Message) { Write-Error $Message }

function Test-Administrator {
    $currentUser = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($currentUser)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

$baseUrl = "{{BASE_URL}}"
$serviceName = "CertCtrlAgent"

$installPath = if ($InstallDir) {
    $InstallDir
} else {
    if ($UserInstall.IsPresent) {
        Join-Path $env:LOCALAPPDATA "Programs\\cert-ctrl"
    } else {
        "C:\\Program Files\\cert-ctrl"
    }
}

$destinationBinary = Join-Path $installPath 'cert-ctrl.exe'

if ($Purge.IsPresent -and -not $Yes.IsPresent) {
    Write-WarningMessage "-Purge will delete the install directory: $installPath"
    $answer = Read-Host "Type 'purge' to continue"
    if ($answer -ne 'purge') {
        Write-ErrorMessage "Purge cancelled."
        exit 1
    }
}

if (-not $UserInstall.IsPresent) {
    if (-not (Test-Administrator)) {
        Write-WarningMessage "Administrator privileges are required to remove the Windows service. Skipping service removal."
    } else {
        try {
            $svc = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
            if ($svc) {
                if ($svc.Status -eq 'Running') {
                    Write-Info "Stopping Windows service '$serviceName'..."
                    if (-not $DryRun.IsPresent) {
                        Stop-Service -Name $serviceName -Force -ErrorAction SilentlyContinue
                    }
                }
                Write-Info "Deleting Windows service '$serviceName'..."
                if (-not $DryRun.IsPresent) {
                    sc.exe delete $serviceName | Out-Null
                }
            }
        } catch {
            Write-WarningMessage "Failed to remove service '$serviceName': $($_.Exception.Message)"
        }
    }
}

if (Test-Path $destinationBinary) {
    Write-Info "Removing $destinationBinary"
    if (-not $DryRun.IsPresent) {
        Remove-Item -Force -Path $destinationBinary
    }
} else {
    if ($Verbose.IsPresent) {
        Write-Info "Binary not present: $destinationBinary"
    }
}

if ($Purge.IsPresent) {
    if (Test-Path $installPath) {
        Write-Info "Removing install directory $installPath"
        if (-not $DryRun.IsPresent) {
            Remove-Item -Recurse -Force -Path $installPath
        }
    }
}

Write-Success "Uninstall complete."
Write-Info "If you installed via PATH changes, you may want to reopen PowerShell."
Write-Info "Help: $baseUrl"
`;